[package]
name = "wgpu_testing"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20"
winit = "0.29"
pollster = "0.3"
bytemuck = { version = "1.15", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
